### ISSUE TITLE
yasmin_viewer not found

### ISSUE THREAD

**Issue by cmravocado** [uleroboticsgroup/yasmin#13]
Thank you for sharing this project. Are there any requirements or dependencies for using yasmin_viewer that aren't specified in the instructions? 

Thanks!

**Comment by mgonzs13** [comment]
Hi @cmravocado, you only need the requirements specified in the [requirements.txt](https://github.com/uleroboticsgroup/yasmin/blob/main/requirements.txt) unless you want to modify the frontend. In that case you need npm and node.

Are you experiencing any errors? If you don't find the yasmin_viewer package, you may need to source your install directory inside you ros2 workspaces.
