### ISSUE TITLE
[Viewer] How to zoom or show only a submachine?

### ISSUE THREAD

**Issue by E-Mans-Application** [uleroboticsgroup/yasmin#26]
Hi,

I'm giving a try to Yasmin, and I want to see a complex state machine (with nested submachines) using the viewer.

The machine is scaled to fit in the window, but that makes it too small to be readable. If I check "Hide Nested FSMs", the names of the submachines become readable, but their substates are hidden.

I need to zoom to specific areas of the machine. When I click on a state, it changes color but does not expand.
Can you provide a way to zoom in and navigate in the graph (e.g. with the mouse)?

I know there is a dropdown that allows to show only one machine, but submachines do not automatically appear in the dropdown list. Only the root machine given to YasminViewerPub appears.

If it is too hard to implement zoom, could you make submachines be added to the dropdown list automatically?

**Comment by mgonzs13** [comment]
Hi @E-Mans-Application, thanks for the issue. Let me think about this, I'll return when I have some advances.

**Comment by reinzor** [comment]
We are also encountering this issue.

**Comment by reinzor** [comment]
Thanks for this library btw!

**Comment by mgonzs13** [comment]
Zoom feature added to the viewer. Here you have an example.

https://github.com/user-attachments/assets/f28fc372-8d07-4840-9054-ef1fa0d04e22

**Comment by reinzor** [comment]
Great!

**Comment by reinzor** [comment]
I think we can close this issue.
