### ISSUE TITLE
State name the same as outcome

### ISSUE THREAD

**Issue by reinzor** [uleroboticsgroup/yasmin#40]
I ran into an issue:

![image](https://github.com/user-attachments/assets/404e26be-36c0-42ab-bbbb-2fc9f747b996)

So in code we are transitioning from the `succeeded` state to the `succeeded` outcome. But the viewer shows something different. I think also this state machine is not correct but it is accepted by the framework. I think it should reject since the behavior is undefined.

**Comment by mgonzs13** [comment]
@reinzor I'll check the viewer. What do you mean with `this state machine is not correct`?

**Comment by reinzor** [comment]
Because how can the transition know it is for the state machine `succeeded` or for the state `succeeded`. They should not have the same name, that shouldn't be allowed I think?

**Comment by mgonzs13** [comment]
Yep, I didn't realize. I'll add this check to the validation in the state machine.

**Comment by mgonzs13** [comment]
53ffd21 checking if the state name is an outcome when adding states should be enough, right?

**Comment by reinzor** [comment]
Should be sufficient yes, great!
