### ISSUE TITLE
ServiceState Demo

### ISSUE THREAD

**Issue by apoorvcn47** [uleroboticsgroup/yasmin#5]
Hi,

Is it possible for you to upload a demo of a ServiceState calling a service? I am not sure how to write a request and response handler.

Thanks

**Comment by mgonzs13** [comment]
Hi @apoorvcn47, I have added a demo for the ServiceState in [Python](https://github.com/uleroboticsgroup/yasmin/blob/main/yasmin_demo/yasmin_demo/service_client_demo.py) and [C++](https://github.com/uleroboticsgroup/yasmin/blob/main/yasmin_demo/src/service_client_demo.cpp).
I hope this can help you.

**Comment by apoorvcn47** [comment]
Thanks @mgonzs13 
This helps. I must say this is an impressive piece of software and I appreciate your hardwork.
Closing this now.
